name: secure_step
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network & WebSocket
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # Location & Permissions
  geolocator: ^12.0.0
  permission_handler: ^11.3.0

  # State & Storage
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  # Audio & Voice
  speech_to_text: ^7.0.0
  record: ^5.1.2
  path_provider: ^2.1.2

  # Sensors & Background
  sensors_plus: ^6.1.0
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^18.0.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Force compatible versions to fix record_linux error
dependency_overrides:
  record_platform_interface: ^1.4.0
  record_linux: ^1.0.0
  record_web: ^1.0.0
  record_windows: ^1.0.0
  record_macos: ^1.0.0

flutter:
  uses-material-design: true